import type { Metadata } from "next";
import "./globals.css";
import "@/app/_asset/theme.scss"
import { childrenProps } from "./_utils/_type/commonType";
import ReactQueryProvider from "./_provider/ReactQueryProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}:childrenProps) {
  return (
    <html lang="ko">
      <body>
      <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
