import type { Metadata } from "next";
import "./globals.css";
import "@/app/_asset/theme.scss";
import "@/app/_asset/home.scss";
import "@/app/_asset/common.scss";
import { childrenProps } from "@/app/type_global/commonType";
import ReactQueryProvider from "./provider/ReactQueryProvider";
import Header from "./components/Header";
import { ReturnPopup } from "@/app/handler/error/ErrorHandler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: childrenProps) {
  return (
    <html lang="ko">
      <body>
        <ReactQueryProvider>
          <div className="wrap">
            <div className="in_wrap">
              <Header />
              {children}
              <ReturnPopup />
            </div>
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
